# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-19 23:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URL', models.URLField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digest', models.CharField(db_index=True, max_length=40, unique=True)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digest', models.CharField(db_index=True, max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=80, unique=True)),
                ('songs', models.ManyToManyField(to='main.Song')),
            ],
        ),
        migrations.AddField(
            model_name='instance',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Song'),
        ),
        migrations.AddField(
            model_name='collection',
            name='instance',
            field=models.ManyToManyField(to='main.Instance'),
        ),
    ]
